# Autogenerated wrapper script for robin_hood_hashing_jll for any
export robin_hood_h

JLLWrappers.@generate_wrapper_header("robin_hood_hashing")
JLLWrappers.@declare_file_product(robin_hood_h)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_file_product(
        robin_hood_h,
        "include/robin_hood.h",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
